### ISSUE TITLE
when I add VSE transform tools to blender, there are some error info

### ISSUE THREAD

**Issue by zextmayamaya** [doakey3/VSE_Transform_Tools#36] opened 2022-02-04 11:45 UTC
Traceback (most recent call last):
  File "D:\blender-3.0.1-windows-x64\3.0\scripts\modules\addon_utils.py", line 387, in enable
    mod.register()
  File "C:\Users\lenovo\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\VSE_Transform_Tools\__init__.py", line 451, in register
    register_class(cls)
ValueError: register_class(...): already registered as a subclass 'PREV_OT_set_cursor_2d'

**Comment by zextmayamaya** [comment] 2022-02-04 11:47
My blender is 3.0.1

**Comment by tin2tin** [comment] 2022-02-04 11:56
The basic transform tools have been implemented in the latest Blender. Open the toolbar in the Preview to see the tools.

**Comment by zextmayamaya** [comment] 2022-02-04 12:59
Thank you so much,

**Comment by zextmayamaya** [comment] 2022-02-04 13:05
The new hotkey is not good for me to use.

**Comment by elgiad007** [comment] 2022-03-12 14:49
What is the new hotkey equivalent to pressing "I" in the preview pane?  This used to show a menu for automatically inserting keyframes for location, scale, rotation, and combinations thereof. I'm not sure how this is done in regular Blender (or what it's even called...)

**Comment by MoralCode** [comment] 2022-07-02 15:16
This issue seems to be a duplicate of #31

**Closed as completed** 2022-11-29 13:52 UTC
